apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: todo-app
type: Opaque
stringData:
  DATABASE_URL: "postgresql://neondb_owner:npg_OnC1e4KspNdk@ep-purple-hat-ahw4nk3o-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require"
  BETTER_AUTH_SECRET: "j6DHo0ZUIVm5pzJAi7wyhd4YOxGqb9gF"
  OPENAI_API_KEY: "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"